CREATE TABLE tb_missoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    dificuldade VARCHAR(255)
);

CREATE TABLE tb_cadastro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    idade INTEGER NOT NULL,
    email VARCHAR(255) UNIQUE,
    img_url VARCHAR(255),
    missoes_id BIGINT,
    CONSTRAINT fk_cadastro_missao
        FOREIGN KEY (missoes_id) REFERENCES tb_missoes (id)
);
